export const LANDING = '/'
export const SEARCH = '/search'
export const PRODUCTONE = '/laptops/123'
export const PRODUCTTWO = '/laptops/682'
export const PRODUCTTHREE = '/laptops/4236'
export const PRODUCTFOUR = '/laptops/96234'